platform :ios, '15.0'

target 'XFeatONNX' do
  use_frameworks!
  pod 'onnxruntime-objc', '~> 1.16'
  pod 'onnxruntime-c', :path => 'Vendors/onnxruntime-c'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
